allowedworlds:
  - world
disallowedblocks:
  - WATER
  - LAVA
  - BUBBLE_COLUMN
  - KELP
  - KELP_PLANT
  - SEAGRASS
  - TALL_SEAGRASS
allowwaterloggedblocks: false
times: 1
center: world_border
radius: world_border